apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 3
  selector:  # Обязательное поле
    matchLabels:
      app: mywebapp
  template:  # Обязательное поле
    metadata:
      labels:  # Обязательное поле
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: nginx:latest
